{ host, ... }:
let
  inherit (import ../../../hosts/${host}/variables.nix) gitUsername;
in
{
  programs.gh.enable = true;

  # GitHub-specific git configuration
  home.file.".config/git/github".text = ''
    [user]
      name = Roman Vassilchenko
      email = 36629811+RomanVassilchenko@users.noreply.github.com
  '';

  programs.git = {
    enable = true;

    # Include secrets file (generated by systemd service)
    includes = [
      { path = "~/.config/git/secrets"; }
      # GitHub-specific configuration
      {
        condition = "hasconfig:remote.*.url:git@github.com:*/**";
        path = "~/.config/git/github";
      }
      {
        condition = "hasconfig:remote.*.url:https://github.com/**";
        path = "~/.config/git/github";
      }
    ];

    ignores = [
      "**/.claude/settings.local.json"
    ];

    settings = {
      # User configuration
      user = {
        name = "${gitUsername}";
        # Email is configured in ~/.config/git/secrets (from encrypted secret)
      };

      # FOSS-friendly settings
      push.default = "simple"; # Match modern push behavior
      credential.helper = "cache --timeout=7200";
      init.defaultBranch = "main"; # Set default new branches to 'main'
      log.decorate = "full"; # Show branch/tag info in git log
      log.date = "iso"; # ISO 8601 date format
      # Conflict resolution style for readable diffs
      merge.conflictStyle = "diff3";

      # URL remapping for SSH access
      url."git@github.com:".insteadOf = "https://github.com/";

      # Delta configuration for better diffs
      core.pager = "delta";
      interactive.diffFilter = "delta --color-only";
      delta = {
        navigate = true;
        light = false;
        side-by-side = true;
        line-numbers = true;
        syntax-theme = "Dracula";
        features = "decorations";
      };
      delta.decorations = {
        commit-decoration-style = "bold yellow box ul";
        file-style = "bold yellow ul";
        file-decoration-style = "none";
      };
      diff.colorMoved = "default";

      # Git aliases
      alias = {
        br = "branch --sort=-committerdate";
        co = "checkout";
        df = "diff";
        dfs = "diff --staged";
        com = "commit -a";
        gs = "stash";
        gp = "pull";
        lg = "log --graph --pretty=format:'%Cred%h%Creset - %C(yellow)%d%Creset %s %C(green)(%cr)%C(bold blue) <%an>%Creset' --abbrev-commit";
        lg2 = "log --graph --oneline --decorate --all";
        st = "status";
        unstage = "reset HEAD --";
        last = "log -1 HEAD";
        visual = "!gitk";
      };
    };
  };
}
