{ host, ... }:
let
  inherit (import ../../../hosts/${host}/variables.nix) gitUsername;
in
{
  programs.gh.enable = true;

  # GitHub-specific git configuration
  home.file.".config/git/github".text = ''
    [user]
      name = Roman Vassilchenko
      email = 36629811+RomanVassilchenko@users.noreply.github.com
  '';

  programs.git = {
    enable = true;

    # Include secrets file (generated by systemd service)
    includes = [
      { path = "~/.config/git/secrets"; }
      # GitHub-specific configuration
      {
        condition = "hasconfig:remote.*.url:git@github.com:*/**";
        path = "~/.config/git/github";
      }
      {
        condition = "hasconfig:remote.*.url:https://github.com/**";
        path = "~/.config/git/github";
      }
    ];

    ignores = [
      "**/.claude/settings.local.json"
    ];

    settings = {
      # User configuration
      user = {
        name = "${gitUsername}";
        # Email is configured in ~/.config/git/secrets (from encrypted secret)
      };

      # FOSS-friendly settings
      push.default = "simple"; # Match modern push behavior
      credential.helper = "cache --timeout=7200";
      init.defaultBranch = "main"; # Set default new branches to 'main'
      log.decorate = "full"; # Show branch/tag info in git log
      log.date = "iso"; # ISO 8601 date format
      # Conflict resolution style for readable diffs
      merge.conflictStyle = "diff3";

      # URL remapping for SSH access
      url."git@github.com:".insteadOf = "https://github.com/";

      # Git maintenance - automatic repository optimization
      maintenance = {
        auto = true;
        strategy = "incremental";
      };

      # Rerere - Reuse recorded resolution of conflicted merges
      rerere = {
        enabled = true;
        autoupdate = true;
      };

      # Better branch display
      branch.sort = "-committerdate";
      column.ui = "auto";

      # Fetch improvements
      fetch = {
        prune = true; # Remove deleted remote branches
        pruneTags = true; # Remove deleted remote tags
        parallel = 0; # Auto-detect parallelism
      };

      # Pull settings
      pull.rebase = true; # Rebase by default instead of merge

      # Rebase improvements
      rebase = {
        autoStash = true; # Automatically stash before rebase
        autoSquash = true; # Auto-squash fixup commits
      };

      # Delta configuration for better diffs
      core.pager = "delta";
      interactive.diffFilter = "delta --color-only";
      delta = {
        navigate = true;
        light = false;
        side-by-side = true;
        line-numbers = true;
        syntax-theme = "Dracula";
        features = "decorations";
      };
      delta.decorations = {
        commit-decoration-style = "bold yellow box ul";
        file-style = "bold yellow ul";
        file-decoration-style = "none";
      };
      diff.colorMoved = "default";

      # Git aliases (shell aliases are in zsh config, these are for git subcommands)
      alias = {
        # Useful as git subcommands
        fixup = "commit --fixup";
        unstage = "reset HEAD --";
        undo = "reset --soft HEAD~1";
        last = "log -1 HEAD";
        conflicts = "diff --name-only --diff-filter=U";
        recent = "for-each-ref --sort=-committerdate --count=10 --format='%(refname:short)' refs/heads/";
        cleanup = "!git branch --merged | grep -v '\\*\\|main\\|master' | xargs -n 1 git branch -d";
      };
    };
  };
}
