[manager]
cwd = { fg = "#@@base0E@@", bold = true }
hovered = { fg = "#@@base00@@", bg = "#@@base0E@@", bold = true }
preview_hovered = { fg = "#@@base00@@", bg = "#@@base0D@@", bold = true }
find_keyword = { fg = "#@@base0A@@", bold = true, italic = true }
find_position = { fg = "#@@base09@@", bg = "#@@base02@@", bold = true }
marker_selected = { fg = "#@@base0B@@", bg = "#@@base0B@@" }
marker_copied = { fg = "#@@base0A@@", bg = "#@@base0A@@" }
marker_cut = { fg = "#@@base08@@", bg = "#@@base08@@" }
tab_active = { fg = "#@@base00@@", bg = "#@@base0E@@", bold = true }
tab_inactive = { fg = "#@@base05@@", bg = "#@@base02@@" }
border_symbol = "│"
border_style = { fg = "#@@base03@@" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#@@base03@@", bg = "#@@base02@@" }
mode_normal = { fg = "#@@base00@@", bg = "#@@base0D@@", bold = true }
mode_select = { fg = "#@@base00@@", bg = "#@@base0B@@", bold = true }
mode_unset = { fg = "#@@base00@@", bg = "#@@base08@@", bold = true }
progress_label = { fg = "#@@base05@@", bold = true }
progress_normal = { fg = "#@@base0E@@", bg = "#@@base02@@" }
progress_error = { fg = "#@@base08@@", bg = "#@@base02@@" }
permissions_t = { fg = "#@@base0D@@" }
permissions_r = { fg = "#@@base0A@@" }
permissions_w = { fg = "#@@base08@@" }
permissions_x = { fg = "#@@base0B@@" }
permissions_s = { fg = "#@@base03@@" }

[select]
border = { fg = "#@@base0E@@" }
active = { fg = "#@@base0E@@", bold = true }
inactive = { fg = "#@@base05@@" }

[input]
border = { fg = "#@@base0E@@" }
title = { fg = "#@@base0E@@", bold = true }
value = { fg = "#@@base05@@" }
selected = { fg = "#@@base00@@", bg = "#@@base0E@@" }

[completion]
border = { fg = "#@@base0D@@" }
active = { fg = "#@@base00@@", bg = "#@@base0D@@", bold = true }
inactive = { fg = "#@@base05@@" }

[tasks]
border = { fg = "#@@base0D@@" }
title = { fg = "#@@base0D@@", bold = true }
hovered = { fg = "#@@base00@@", bg = "#@@base0D@@" }

[which]
mask = { bg = "#@@base01@@" }
cand = { fg = "#@@base0E@@", bold = true }
rest = { fg = "#@@base03@@" }
desc = { fg = "#@@base0D@@" }
separator = " 󰁔 "
separator_style = { fg = "#@@base03@@" }

[help]
on = { fg = "#@@base0E@@", bold = true }
run = { fg = "#@@base0C@@" }
desc = { fg = "#@@base05@@" }
hovered = { fg = "#@@base00@@", bg = "#@@base0E@@", bold = true }
footer = { fg = "#@@base03@@" }

[filetype]
rules = [
  { mime = "image/*", fg = "#@@base0A@@" },
  { mime = "video/*", fg = "#@@base09@@" },
  { mime = "audio/*", fg = "#@@base09@@" },
  { mime = "application/zip", fg = "#@@base08@@" },
  { mime = "application/gzip", fg = "#@@base08@@" },
  { mime = "application/x-tar", fg = "#@@base08@@" },
  { mime = "inode/x-empty", fg = "#@@base03@@" },
  { mime = "*", is = "orphan", fg = "#@@base08@@" },
  { mime = "*", is = "exec", fg = "#@@base0B@@" },
  { mime = "*/", fg = "#@@base0E@@", bold = true },
]
